spring:
  datasource:
    url: ${url}
    username: ${user}
    password: ${password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
